# Uncomment the next line to define a global platform for your project
platform :ios, '16.4'

target 'SwiftUILoginPage' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'Alamofire'

  # Pods for SwiftUILoginPage

end

target 'SwiftUILoginPageTests' do
  inherit! :search_paths
  pod 'Alamofire'
end
